name:                 hjq
version:              0.1.0.0
visibility:           public
id:                   hjq-0.1.0.0-Lt0UvNNuhK74ZMIFmzcY5B
key:                  hjq-0.1.0.0-Lt0UvNNuhK74ZMIFmzcY5B
license:              BSD-3-Clause
copyright:            2026 Author name here
maintainer:           example@example.com
author:               Author name here
homepage:             https://github.com/githubuser/hjq#readme
description:
    Please see the README on GitHub at <https://github.com/githubuser/hjq#readme>

abi:                  acf5b7219c95bd87793ad8cdf125b17f
exposed:              True
exposed-modules:      Lib
hidden-modules:       Paths_hjq
import-dirs:
    /home/r-yamamoto/repos/github.com/re2osushi8888/sandbox/hjq/.stack-work/install/x86_64-linux/9b95456112eef7de696b363e223eb888e40ed917d4385554d03486a2a2164c62/9.6.7/lib/x86_64-linux-ghc-9.6.7/hjq-0.1.0.0-Lt0UvNNuhK74ZMIFmzcY5B

library-dirs:
    /home/r-yamamoto/repos/github.com/re2osushi8888/sandbox/hjq/.stack-work/install/x86_64-linux/9b95456112eef7de696b363e223eb888e40ed917d4385554d03486a2a2164c62/9.6.7/lib/x86_64-linux-ghc-9.6.7/hjq-0.1.0.0-Lt0UvNNuhK74ZMIFmzcY5B

library-dirs-static:
    /home/r-yamamoto/repos/github.com/re2osushi8888/sandbox/hjq/.stack-work/install/x86_64-linux/9b95456112eef7de696b363e223eb888e40ed917d4385554d03486a2a2164c62/9.6.7/lib/x86_64-linux-ghc-9.6.7/hjq-0.1.0.0-Lt0UvNNuhK74ZMIFmzcY5B

dynamic-library-dirs:
    /home/r-yamamoto/repos/github.com/re2osushi8888/sandbox/hjq/.stack-work/install/x86_64-linux/9b95456112eef7de696b363e223eb888e40ed917d4385554d03486a2a2164c62/9.6.7/lib/x86_64-linux-ghc-9.6.7

data-dir:
    /home/r-yamamoto/repos/github.com/re2osushi8888/sandbox/hjq/.stack-work/install/x86_64-linux/9b95456112eef7de696b363e223eb888e40ed917d4385554d03486a2a2164c62/9.6.7/share/x86_64-linux-ghc-9.6.7/hjq-0.1.0.0

hs-libraries:         HShjq-0.1.0.0-Lt0UvNNuhK74ZMIFmzcY5B
depends:              base-4.18.3.0
haddock-interfaces:
    /home/r-yamamoto/repos/github.com/re2osushi8888/sandbox/hjq/.stack-work/install/x86_64-linux/9b95456112eef7de696b363e223eb888e40ed917d4385554d03486a2a2164c62/9.6.7/doc/hjq-0.1.0.0/hjq.haddock

haddock-html:
    /home/r-yamamoto/repos/github.com/re2osushi8888/sandbox/hjq/.stack-work/install/x86_64-linux/9b95456112eef7de696b363e223eb888e40ed917d4385554d03486a2a2164c62/9.6.7/doc/hjq-0.1.0.0
