name:                 hjq
version:              0.1.0.0
visibility:           public
id:                   hjq-0.1.0.0-CYb1jdNc2NY1jCkZwouTLF
key:                  hjq-0.1.0.0-CYb1jdNc2NY1jCkZwouTLF
license:              BSD-3-Clause
copyright:            2026 Author name here
maintainer:           example@example.com
author:               Author name here
homepage:             https://github.com/githubuser/hjq#readme
description:
    Please see the README on GitHub at <https://github.com/githubuser/hjq#readme>

abi:                  f5d087fdc62dd2cdb2623de8f30a1164
exposed:              True
exposed-modules:      Lib
hidden-modules:       Paths_hjq
import-dirs:
    /home/r-yamamoto/repos/github.com/re2osushi8888/sandbox/hjq/.stack-work/install/x86_64-linux/84d434dca807a52b1eb4989ec94367a6957625f279cc790322dc146486edfb90/9.6.7/lib/x86_64-linux-ghc-9.6.7/hjq-0.1.0.0-CYb1jdNc2NY1jCkZwouTLF

library-dirs:
    /home/r-yamamoto/repos/github.com/re2osushi8888/sandbox/hjq/.stack-work/install/x86_64-linux/84d434dca807a52b1eb4989ec94367a6957625f279cc790322dc146486edfb90/9.6.7/lib/x86_64-linux-ghc-9.6.7/hjq-0.1.0.0-CYb1jdNc2NY1jCkZwouTLF

library-dirs-static:
    /home/r-yamamoto/repos/github.com/re2osushi8888/sandbox/hjq/.stack-work/install/x86_64-linux/84d434dca807a52b1eb4989ec94367a6957625f279cc790322dc146486edfb90/9.6.7/lib/x86_64-linux-ghc-9.6.7/hjq-0.1.0.0-CYb1jdNc2NY1jCkZwouTLF

dynamic-library-dirs:
    /home/r-yamamoto/repos/github.com/re2osushi8888/sandbox/hjq/.stack-work/install/x86_64-linux/84d434dca807a52b1eb4989ec94367a6957625f279cc790322dc146486edfb90/9.6.7/lib/x86_64-linux-ghc-9.6.7

data-dir:
    /home/r-yamamoto/repos/github.com/re2osushi8888/sandbox/hjq/.stack-work/install/x86_64-linux/84d434dca807a52b1eb4989ec94367a6957625f279cc790322dc146486edfb90/9.6.7/share/x86_64-linux-ghc-9.6.7/hjq-0.1.0.0

hs-libraries:         HShjq-0.1.0.0-CYb1jdNc2NY1jCkZwouTLF
depends:              base-4.18.3.0
haddock-interfaces:
    /home/r-yamamoto/repos/github.com/re2osushi8888/sandbox/hjq/.stack-work/install/x86_64-linux/84d434dca807a52b1eb4989ec94367a6957625f279cc790322dc146486edfb90/9.6.7/doc/hjq-0.1.0.0/hjq.haddock

haddock-html:
    /home/r-yamamoto/repos/github.com/re2osushi8888/sandbox/hjq/.stack-work/install/x86_64-linux/84d434dca807a52b1eb4989ec94367a6957625f279cc790322dc146486edfb90/9.6.7/doc/hjq-0.1.0.0
